### ISSUE TITLE
Exception thrown trying to createScenesAsync()

### ISSUE THREAD

**Issue by Dinnerbone** [mixer/interactive-java#63]
https://github.com/mixer/interactive-java/blob/c90c086b9e9b7a222cd86eae8cfcf36fea65aa5b/src/main/java/com/mixer/interactive/services/SceneServiceProvider.java#L263

On this line, a `Collection<InteractiveScene>` is trying to be serialized as `InteractiveScene[]`. This throws the following exception:

```
java.lang.IllegalArgumentException: Argument is not an array
	at java.lang.reflect.Array.getLength(Native Method)
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:91)
	at com.google.gson.Gson.toJson(Gson.java:593)
	at com.google.gson.Gson.toJsonTree(Gson.java:486)
	at com.mixer.interactive.services.SceneServiceProvider.createScenesAsync(SceneServiceProvider.java:263)
	at com.mixer.interactive.services.SceneServiceProvider.createScenesAsync(SceneServiceProvider.java:218)
```

**Comment by pahimar** [comment]
Resolved with https://github.com/mixer/interactive-java/commit/baf7646220c57ab3fdd59cf1a6c7b03d7c3fe523
