### ISSUE TITLE
Can't get scenes if labels exist

### ISSUE THREAD

**Issue by funniray** [mixer/interactive-java#85]
Hey, whenever I try to get the controls using 
```Java
client.using(GameClient.CONTROL_SERVICE_PROVIDER).getControls().get();
```
I get `java.util.concurrent.ExecutionException: java.lang.NullPointerException`. I'm using `com.mixer:mixer-interactive-api:3.0.0`. When the request is sent, the game isn't in a "Ready" state. I'm not sure if that has anything to do with it but I really don't know. My code worked 1-2 months ago but something changed and now I `java.util.concurrent.ExecutionException: java.lang.NullPointerException` on that line...

**Comment by funniray** [comment]
I've kept trying and trying but I can't get it to work. This is the stack trace I get and I can't make any sense of it

[17:05:22 INFO]: [Mixer] Interactive connected!
[17:05:22 WARN]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[17:05:22 WARN]: 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
[17:05:22 WARN]: 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
[17:05:22 WARN]: 	at pro.kdray.funniray.mixer.handlers.Interactive.onConnectionEsablished([Interactive.java:84](https://github.com/funniray/Mixer/blob/bac1f36c90ed6013ae53d8be395c12b3527d1a2a/mixer-common/src/main/java/pro/kdray/funniray/mixer/handlers/Interactive.java#L84))

**Comment by funniray** [comment]
After a bit of testing I've found that labels end up making the library error out.
